### ISSUE TITLE
.split() isn't a generator!

### ISSUE THREAD

**Issue by theelous3** [Zaab1t/bong#1]
In `terms_in_document` you use `.split()` and mention in the docstring you're returning a generator, but `.split()` is not a generator. You're making a massive list.

I used: https://github.com/ivoronin/python-isplit

And searched a 100mb file. Reduced memory usage by just under half.
 * isplit version used a max of :    351.2 MiB
 * split version used a max of :     620.7 MiB

```py
import isplit

def terms_in_document(document, delimiter=' '):
    return isplit.isplit(document, ' ')
```

Note, you could probably just move that right in to the `super()` call. Don't really need to alias `.split()`.

Memory usage was taken with memory_profiler : https://github.com/fabianp/memory_profiler

I'm sure there's even more wiggle room to get that memory usage down. 100MB file racking up 350mb sill seems excessive. I think it's due to the use of `Counter`.

(I did lazily read the whole file in to memory, so iteratively building the `Counter` would be the way to go I think. Still doesn't account for it all though.)

**Comment by carlbordum** [comment]
I'm not sure we can get much better performance without Counter. It is highly optimized. However, you are completely correct that `terms_in_document` is not returning a generator, is a burden to the programme and an unnecessary alias of `str.split()`. The reason it is there, is because I have plans for finding the terms in a more advenced way (YAGNI, I know). For instance, "New York" should be a single term and I would also like to remove some words that adds no semantic value.

**Comment by theelous3** [comment]
Yeah, I was playing around writing my own generator versions of split but regardless of how optimised I made them they were many times slower than that c extension `isplit` or the builtin (also c) .`split`.

Getting more nuanced behaviour on that front will be a challenge, though much of it can be solved by pre-processing documents. For example, store sets of `.isplit`s of each document along side them, where all cases have non-letter or alphanumeric values removed. The small added overhead of hard drive space is far less valuable than the memory or cpu.

In fact, lemme go and test that out.
